# It's possible the controller manager is running in a namespace
controller_manager_ns: open_manipulator_6dof

controller_list:
  # This controller is for your ARM
  - name: arm_controller  # <-- MUST EXACTLY MATCH the name from your topics
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint1 # Or whatever your arm's joint names are
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

  # This controller is for your GRIPPER
  - name: gripper_controller # <-- MUST EXACTLY MATCH the name from your topics
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - gripper # Or whatever your gripper's joint names are
      - gripper_sub